### ISSUE TITLE
Swap side feature will be nice

### ISSUE THREAD

**Issue by mluvw47** [moshfeu/vscode-diff-merge#1]
Thanks for making this tool. 

I was looking for side by side merge tools (like beyond compare), it somehow found something u have done. 

As first time user,  I launch the tool, I thought it has a way to swap the two files side on the editor. 
I want to merge something from A to B.
When I open the file A on the editor, right click select your tool, and select the file B. 
I didn't expect it is the file B, will be merge to A instead. (I should have read the careful, when i right click launching the tool, (Diff tool & merge file to))
The tool only can do one side merge (Left to Right)

If on the top menu, u can do an icon, or something like swap side (A->B) or (B->A), that would be helpful.

**Comment by moshfeu** [comment]
Thanks you for the feedback.
Indeed it's an important feature and I'll definitely will add it soon.

**Comment by mluvw47** [comment]
Indeed, thank you doing that.

**Comment by awarmfastbear** [comment]
You may be able to gain some insight on how to do pane swapping by seeing how this package does it: https://marketplace.visualstudio.com/items?itemName=L13RARY.l13-diff

**Comment by moshfeu** [comment]
> You may be able to gain some insight on how to do pane swapping by seeing how this package does it: https://github.com/l13/vscode-diff#user-content-basics

Thanks! I'll look on it.

**Comment by moshfeu** [comment]
BTW, Nice extension :) 
I made a similar extension: https://github.com/moshfeu/vscode-compare-folders/
https://marketplace.visualstudio.com/items?itemName=moshfeu.compare-folders

**Comment by moshfeu** [comment]
I made a version with that feature, can you take a look?
Thanks!

[diff-merge-0.1.0.vsix.zip](https://github.com/moshfeu/vscode-diff-merge/files/4029144/diff-merge-0.1.0.vsix.zip)

**Comment by mluvw47** [comment]
sorry, how to install the zip file, I am using Ubuntu, is that easier to just release a 0.1.0 version?

**Comment by awarmfastbear** [comment]
This works great, thank you!!

**Comment by moshfeu** [comment]
> sorry, how to install the zip file, I am using Ubuntu, is that easier to just release a 0.1.0 version?

@mluvw47 
I want to make sure that it's working so I'm happy you have Ubuntu because I have not :)

Just unzip it. Inside there is .VSIX file which you can install very easy from the extension tab.

<img width="590" alt="Screen Shot 2020-01-07 at 23 26 36" src="https://user-images.githubusercontent.com/3723951/71930889-3e21f880-31a5-11ea-8e07-9be70cf67054.png">

Thanks!

**Comment by mluvw47** [comment]
I uninstalled the old version I got, unzip zip file and then install the .vsix, the version show 0.10, However, when I click the "[Diff & Merge] choose a file to merge", nothing happen. (It used to show a separate dialog and allow to compare/merge another file"?

**Comment by awarmfastbear** [comment]
> I uninstalled the old version I got, unzip zip file and then install the .vsix, the version show 0.10, However, when I click the "[Diff & Merge] choose a file to merge", nothing happen. (It used to show a separate dialog and allow to compare/merge another file"?

I noticed that the window to manually select another file is also gone. If you select two file files in the explorer view, does the Diff & Merge option work for you?

@moshfeu may still be incorporating the logic to show that location window popup if two files aren't selected.

**Comment by moshfeu** [comment]
Thanks! I'll check and fix that soon.

**Comment by moshfeu** [comment]
I fixed it. I really appreciate if you can take another (and final, I hope) look.
Many thanks!


[diff-merge-0.1.1.vsix.zip](https://github.com/moshfeu/vscode-diff-merge/files/4042551/diff-merge-0.1.1.vsix.zip)

**Comment by mluvw47** [comment]
I verified the version u post above the dialog got pop up to select a file to merged to. 
However, I don't see the a way to swap side. 

![image](https://user-images.githubusercontent.com/18360450/72301777-b9a7fd80-361c-11ea-8237-65ef8a9545fd.png)

**Comment by moshfeu** [comment]
<img width="340" alt="Screen Shot 2020-01-14 at 8 49 53" src="https://user-images.githubusercontent.com/3723951/72320710-ec98d280-36aa-11ea-8569-54300b2dc476.png">

Do you see the icon in the top right toolbar?
