### ISSUE TITLE
Basic usage?

### ISSUE THREAD

**Issue by poldim** [moshfeu/vscode-diff-merge#102]
I feel dumb for making this isssue, but how do I do basic things like go through one diff at a time and choose whether to merge left/merge right?  All I can find are these commands: 
<img width="170" alt="image" src="https://user-images.githubusercontent.com/16869713/202508032-2a7747ce-2916-4b31-844d-dae38cfeec86.png">

**Comment by moshfeu** [comment]
Hi. sorry for the delayed reply.
The is a gray right arrow between each diff that copies the left diff into the right one (see the picture).

I must say that vscode now has this feature built-in so this extension is no longer needed for merging 2 existing files
