### ISSUE TITLE
File loaded incomplete

### ISSUE THREAD

**Issue by renanlq** [moshfeu/vscode-diff-merge#14]
Hi Mosh,

Think that we have an unusual scenario here. When trying to compare a huge file, 30 thousand lines, the file loaded for Diff & Merge extension is missing lots of them.

Visual Studio Diff native:
![2020-06-15_15h16_55](https://user-images.githubusercontent.com/15347353/84693112-5862be00-af1d-11ea-9676-f6bef40400a9.png)
![2020-06-15_15h17_03](https://user-images.githubusercontent.com/15347353/84693118-5993eb00-af1d-11ea-9702-436f205fe984.png)

Diff merge extension:
![2020-06-15_15h20_20](https://user-images.githubusercontent.com/15347353/84693119-5b5dae80-af1d-11ea-8120-bb37e1f8900e.png)
![2020-06-15_15h20_30](https://user-images.githubusercontent.com/15347353/84693121-5c8edb80-af1d-11ea-9413-634988699568.png)

**Visual Studio version**:
Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

**Extension version**: v0.2.4

**Comment by moshfeu** [comment]
Thank for the issue!
Can you send me the file so I could test it?
You can remove any sensitive data as long as the structure remain the same. I want to make sure that the size is the problem but not something with the format.

**Comment by moshfeu** [comment]
I think I found the issue. The extension run `git diff -U1000` which takes only 1000 lines.
I wonder which number I should use.. 30k?

**Comment by moshfeu** [comment]
I just implemented it. Please download the zip ([from the PR](https://github.com/moshfeu/vscode-diff-merge/pull/23#issue-486052719)), unzip it (to .vsix file) and check if it solves the issue.

Thanks 🙏

**Comment by renanlq** [comment]
@moshfeu, really sorry for not giving you any response since I opened this issue, due to we move to default diff from VSCode, I forgot this thread, sorry about that.

And sorry to not send you the main file used in this issue, just to keep here the information: it was full profile.xml file retrieved from Salesforce CRM.
