### ISSUE TITLE
diff and merge losing icons in find mode

### ISSUE THREAD

**Issue by dixitk13** [moshfeu/vscode-diff-merge#19]
If I use diff and merge tool and do a `Ctrl + F` in the file, it loses the Icons: 

<img width="538" alt="Screen Shot 2020-08-19 at 4 20 39 PM" src="https://user-images.githubusercontent.com/8632659/90699382-02213c80-e238-11ea-8b90-55fe7b478079.png">

**Comment by moshfeu** [comment]
Thanks for the report!
I'll check it soon.

**Comment by moshfeu** [comment]
It's still not clear to me how to solved it but found a related issue (attach above).
Waiting for response 🤞

**Comment by moshfeu** [comment]
Turned out it's not related to that attached issue. I found the solution and a PR in its way.

**Comment by moshfeu** [comment]
Can you test the fixed version please?
https://github.com/moshfeu/vscode-diff-merge/releases/download/v0.2.5/diff-merge-0.2.5.vsix

**Comment by dixitk13** [comment]
LGTM 👍 
<img width="902" alt="Screen Shot 2020-08-29 at 12 44 21 PM" src="https://user-images.githubusercontent.com/8632659/91646243-10bedf00-ea02-11ea-99a3-3b3d7eb4e8fb.png">

**Comment by moshfeu** [comment]
Thanks!
