### ISSUE TITLE
When two files are selected in the Explorer allow them to be Diff&Merge'd

### ISSUE THREAD

**Issue by awarmfastbear** [moshfeu/vscode-diff-merge#2]
Thank you so much for making this, it's a great help. One UX limitation I found is that I'd like to be able to diff and merge two files that I already have selected. Much like how you are able to compare two files in VS Code by highlighting them both and clicking Compare Selected. I want to be able to highlight two files in the left view and be able to choose 'Diff&Merge' selected.

Currently I have to paste in the path of the second file or manually navigate to it.

Thank you! :)

**Comment by moshfeu** [comment]
Thank you 😊
This is a great feature. I'll do it as soon as I'll have some time.
P.S. if you know how to do this, feel free to create a PR.

**Comment by moshfeu** [comment]
I made a version with that feature, can you take a look?
Thanks!

[diff-merge-0.1.0.vsix.zip](https://github.com/moshfeu/vscode-diff-merge/files/4029144/diff-merge-0.1.0.vsix.zip)

**Comment by awarmfastbear** [comment]
AWESOME! This works exactly as I expected!!! Thank you!!

**Comment by moshfeu** [comment]
It took me some time to complete it, but it's done.
Thank you!
