### ISSUE TITLE
It's not compatible with the SVN extention

### ISSUE THREAD

**Issue by moonlightsh** [moshfeu/vscode-diff-merge#21]
It doesn't work fine with the SVN extention to show what has been changed.

**Comment by moshfeu** [comment]
Thanks for the report.
Can you post the link to the svn extension? I'm not familiar with it.

**Comment by moonlightsh** [comment]
Here is the SVN extention: https://marketplace.visualstudio.com/items?itemName=johnstoncode.svn-scm.

SVN is another revision control tool similar with git, reference https://en.wikipedia.org/wiki/Apache_Subversion.
The SVN extention, can be used for the SVN controled project to replace git.

**Comment by moshfeu** [comment]
Thanks. I'll try it out and see if there's anything I can do.

**Comment by moshfeu** [comment]
I just implemented it. Please download the zip ([from the PR](https://github.com/moshfeu/vscode-diff-merge/pull/23#issue-486052719)), unzip it (to .vsix file) and check if that what you meant.

Thanks 🙏
