### ISSUE TITLE
Some Feedback

### ISSUE THREAD

**Issue by j12y** [moshfeu/vscode-diff-merge#22]
First off, thank you for making this project / extension available. 

I brought up in another issue that I had given it a try:
https://github.com/microsoft/vscode/issues/25887 

A few issues I ran into: 
- compared two files, made changes based on diff (just yaml file), saved, but it didn't update the file on disk so I couldn't complete the task
- I use vim extension but in diff view the extension stopped working

Other UX observation:
- selected two files in my workspace but opened order was wrong since merge is one-way, when i swapped it jumped to a different place in the file which was jarring but not too big of a deal
- selected file to edit in my workspace and then "Choose a file to merge" which opened a file explorer, not a big deal but the file i wanted was in same directory so had to navigate back to my workspace

Hope that helps.

**Comment by moshfeu** [comment]
Thank you!

> compared two files, made changes based on diff (just yaml file), **saved**.. 

How did you saved? Have you noticed the changes indication has gone?

![video1](https://user-images.githubusercontent.com/3723951/93004751-ba4db680-f552-11ea-9e2e-0475e10bc9b6.gif) 

---------------------
> I use vim extension but in diff view the...
I'm not familiar with the vim extension, I'll take a look.

---------------------
> ....selected two files in my workspace but opened order...
It's a nice improvement. I'll try to get to this.

---------------------
If both of the files are at the same workspace, you can choose both of them -> right click -> [Diff & Merge] Compare selected

**Comment by j12y** [comment]
I did a command+s which did remove the unsaved badge but file was unchanged.  I can give it another try next time I'm merging to see if there is an explanation or user error 😮.

**Comment by moshfeu** [comment]
I tested it yesterday and it worked fine. I'd love to get a reproducible scenario.
Thanks!

**Comment by moshfeu** [comment]
Keep it

**Comment by moshfeu** [comment]
Took me some time :)

About that:

> selected file to edit in my workspace and then "Choose a file to merge" which opened a file explorer, not a big deal but the file i wanted was in same directory so had to navigate back to my workspace

What is the expected ux?
If it's not at the same workspace - you can use the file explorer. If they have, you can choose both of them -> right click -> [Diff & Merge] Compare selected.

Also, can you check again if the saving still not working?
I'll look on the vim extension but since the diff view is basically a [Webview](https://code.visualstudio.com/api/extension-guides/webview) all the extension who affect on the Editor, likely won't work.
