### ISSUE TITLE
Show diff in selected color scheme

### ISSUE THREAD

**Issue by babobski** [moshfeu/vscode-diff-merge#24]
Would be nice if the diff screen would respect the current selected color scheme.

**Comment by moshfeu** [comment]
Thanks! Actually, it meant to respect as much as possible. See [#known-issues](/moshfeu/vscode-diff-merge#known-issues) (section 2)

https://github.com/moshfeu/vscode-diff-merge/blob/9ad0cdf7fb6677bb62ebd91768e1a309c063ff63/README.md#L72
