### ISSUE TITLE
Merge with clipboard

### ISSUE THREAD

**Issue by babobski** [moshfeu/vscode-diff-merge#25]
Would be nice to have a function to merge with clipboard

**Comment by moshfeu** [comment]
Thanks for the idea.
Do you mean to compare a file against the clipboard?
Maybe you can elaborate a bit about it.

BTW, there is a workaround by [calling the command](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) `[Diff & Merge] Blank diff view`. It's not convenient, I know :)

**Comment by jay-pee** [comment]
Look at the "compare active file with clipboard" function that is already implemented in vs code... I think the author want to have it like this. At least me would love this feature ;)

**Comment by moshfeu** [comment]
I've created a PR with this feature. I'd love you to test it and give a feedback.


[diff-merge-0.4.0.vsix.zip](https://github.com/moshfeu/vscode-diff-merge/files/5505510/diff-merge-0.4.0.vsix.zip)

**Comment by jay-pee** [comment]
I will have a look in the next days

**Comment by babobski** [comment]
@moshfeu Just tested the function, but it's not working for me. It's inserting the wrong values from the left side. 
But thanks for adding the functionality.

**Comment by moshfeu** [comment]
Moved the discussion to #29
