### ISSUE TITLE
total failure because remove all empty lines

### ISSUE THREAD

**Issue by clembo590** [moshfeu/vscode-diff-merge#27]
First Thank for your plugin. It could / should / will be a great additionnal feature but there are still "big bugs"

I have a file that I have modified just by adding a few empty lines.

when comparing it with your plugin
important: On the top of the picture is the default diff of vscode, on the bottom is the diff made by your plugin

1) all empty lines are not shown. (which is not a big issue)
<img width="2084" alt="Screenshot 2020-11-17 at 13 02 00" src="https://user-images.githubusercontent.com/10899818/99388329-b2551e80-28d5-11eb-93bb-2cdd2e896594.png">

2) when I just click on the "little arrow" to copy from left to right and then save.
here is what I get: all empty lines of the files have been removed and so my file has been completly changed...
<img width="2085" alt="Screenshot 2020-11-17 at 13 05 41" src="https://user-images.githubusercontent.com/10899818/99388392-d0228380-28d5-11eb-80dc-84fc07264e94.png">

**Comment by moshfeu** [comment]
Thanks for reporting this!
I'll try to reproduce and let you know.

**Comment by moshfeu** [comment]
I can't reproduce the issue :\
![video1](https://user-images.githubusercontent.com/3723951/99601746-b3d33380-2a08-11eb-8992-b7fbe5a6006a.gif)

Can you share the minimum **content** of the files that can reproduce the issue?
Also, about the 2nd section, as far as I know, saving shouldn't change the content but only saving the file to the file system. Are you still sure that the content changed after **saving**? If not, what the steps to reproduce?
Thanks

**Comment by clembo590** [comment]
sure:
here is a basic file content:
https://drive.google.com/drive/folders/1Pz3zxWBeXt_a3sayOa5AFbLTU_EWAltM?usp=sharing

Once you have the file, add it a repo. (commit)

then make a change "around end of file" (and do not commit).
then compare it with your plugin.
![Screenshot 2020-11-19 at 12 55 04](https://user-images.githubusercontent.com/10899818/99663284-a3ea3c80-2a66-11eb-86dd-a0599b071b9b.png)

--> as you can see on the picture (UP IS THE REAL ACTUAL FILE), on line 2 there should be an empy line.
and it s not shown in your plugin....
(I think once this issue is solved then the second issue will "disappear")

**Comment by moshfeu** [comment]
@clembo590 can you [install](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) this version and tell me if it works as expected for you?
Thanks!

[diff-merge-0.4.1.vsix.zip](https://github.com/moshfeu/vscode-diff-merge/files/5578364/diff-merge-0.4.1.vsix.zip)

**Comment by clembo590** [comment]
Hello @moshfeu 
I just checked and it seems to be working PERFECTLY now!
thanks a lot.

**Comment by moshfeu** [comment]
So happy to hear :)
I'll publish this fix asap.
Thanks for your collaboration!

**Comment by moshfeu** [comment]
Published (0.4.1)
