### ISSUE TITLE
Start VSCode with this extension from the command line

### ISSUE THREAD

**Issue by FrancoisMongeau** [moshfeu/vscode-diff-merge#3]
Thank you **very much** for making this extension.
I'd like to be able to start it from the command line; eg right now I can do:
`code --diff <file> <file>`
I'd like to be able to do:
`code --diff&merge <file> <file>`
or (simpler syntax):
`code --merge <file> <file>`
I'm not technical enough to do this myself.

**Comment by moshfeu** [comment]
Thank you!
I'm not sure it's possible but I'll check.

**Comment by moshfeu** [comment]
I can't find a way to do this right now. As you can see I opened an issue to see if I'm missing something. Also you can see there the workaround I found. It will look like that:

```
MERGE=<file> code <file>
```

I don't think that it's a good solution but it could work. Interesting?

**Comment by VinnieCool** [comment]
How about overriding the code/monaco diff view with this ext

**Comment by moshfeu** [comment]
@VinnieCool I don't think it's possible :/
That's why I added new options in the context menus.
If you know a way, I'll be happy to hear!
Also, please create another issue to discuss about that..

**Comment by moshfeu** [comment]
Sadly, currently I can't do it so I'm closing it for now.
If, one day, it will be possible, please re-open it.
