### ISSUE TITLE
 Please publish the extension to Open VSX

### ISSUE THREAD

**Issue by eternal-sorrow** [moshfeu/vscode-diff-merge#31]
Hi!

I'm a VS Code-OSS user, a FLOSS version of VS Code, it's the same code but without the Microsoft's telemetry and branding.

I want to request if it's possible to add this extension on the open-vsx.org marketplace, because it's unclear if Microsoft marketplace is legal to use on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).

This is [how to](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) publish a new extension.

Thanks.

**Comment by moshfeu** [comment]
Will do soon.
Thanks for the request!

**Comment by moshfeu** [comment]
Just did - https://open-vsx.org/extension/moshfeu/diff-merge.
Let me know if it's working as expected for you because I'm not sure it packaged correctly.

**Comment by eternal-sorrow** [comment]
Tried it, it works! Thanks!

**Comment by moshfeu** [comment]
Thank you :)
