### ISSUE TITLE
Swaping wrong line

### ISSUE THREAD

**Issue by abhi7705** [moshfeu/vscode-diff-merge#34]
![image](https://user-images.githubusercontent.com/11956373/107211031-febe7f00-6a2a-11eb-80b7-2cc0fcc37124.png)
When I compare and try to move some line from A-> By clicking on (-->)  it's moving the same line 

Should this move the same line to B or This functionality is not added?

**Comment by abhi7705** [comment]
![image](https://user-images.githubusercontent.com/11956373/107211505-a89e0b80-6a2b-11eb-85e7-6c7103e1d1fd.png)
is this arrow for moving the line from left to right?

**Comment by moshfeu** [comment]
Yes, it should.
Is this working in other diffs / files?
Can you send me the content of the files so I could try to reproduce the issue?
You can send them to moshfeu.dev@gmail.com

**Comment by abhi7705** [comment]
yes it's working on few places in other file.
One more question :
can I move few changes from A to B and after changing sides from B to A?

I am gonna mail both file to you

**Comment by moshfeu** [comment]
I think I fixed it. Can you verify please before I publish?
Thanks!
[diff-merge-0.4.3.vsix.zip](https://github.com/moshfeu/vscode-diff-merge/files/5969254/diff-merge-0.4.3.vsix.zip)

**Comment by abhi7705** [comment]
Yes, It's working fine now.
Thanks!!
