### ISSUE TITLE
diff-merge not working with theia

### ISSUE THREAD

**Issue by Seza** [moshfeu/vscode-diff-merge#36]
Theia is a IDE fully compatible with VSCODE api and extension. 

diff-merge actually not working in theia. I don’t where is the problem, if it’s diff-merge or a theia workaround. 

I submit here a report because merging (2 or 3 column) is a big lack in theia and diff-merge is the only response a this point.

**Comment by moshfeu** [comment]
Hi,
I'm not familiar with Theia.
I'll try to play with it and see what I can do

**Comment by moshfeu** [comment]
Hi,
I'm not familiar with Theia.
I'll try to play with it and see what I can do

**Comment by Seza** [comment]
That’s great you take a look at ;)
