### ISSUE TITLE
vscode marketplace installs old version 0.4.2

### ISSUE THREAD

**Issue by madeddy** [moshfeu/vscode-diff-merge#37]
Extension browser in vscode shows also just 0.4.2 if i search for this. I needed to DL & install 0.4.3 manual.

Perhaps a bit minor to open a issue about this and possibly the wrong place(Is the problem with marketplace? Not here?), but didn know how/where else. (This would have fitted nicely in the new repository "Diskussions" feature which can be activated in github settings.)

The changelog is also not up to date > 0.4.0 ...

**Comment by moshfeu** [comment]
Seems like the latest marketplace latest version is 0.4.3 now. Maybe there was a delay.
The changelog shows only minor versions because no features added in the patch versions.

**Comment by madeddy** [comment]
Thats good. Ok, thanks for taking the time and the info.
Closed with this.
