### ISSUE TITLE
View diff across editor groups

### ISSUE THREAD

**Issue by madeddy** [moshfeu/vscode-diff-merge#38]
[Enhancement]
I work most of the time with 2 editor group columns. If i open now a file diff it appears in one group and with this half of the horizontal space. Essentially i get as diff view consistent of two small stripes of code and see a sh*t. As user i need now to resize(minimize width) of the other editor group.

Don't know if the API even allows this.

**Comment by moshfeu** [comment]
Let me make sure I understand.
When you have 2 groups you want to show the diff editor like there is only one group (takes the full width of vscode)?

If so, I agree that it's probably not possible and probably don't comply with the vscode ui.

**Comment by madeddy** [comment]
Argh, frustrating. 😢  How limited this is in vscode... Thanks anyways for taking the time. 👋🏻 
I work for now with a unified diff, so i do not need to try and make sense out of two small slits of code.

As there will be no solution to this, i close it. Greets
