### ISSUE TITLE
honor editor.tabSize in monaco

### ISSUE THREAD

**Issue by VinnieCool** [moshfeu/vscode-diff-merge#4]

**Comment by moshfeu** [comment]
Good feature.
Thanks!

**Comment by moshfeu** [comment]
Seems like I can't set the `tabSize` in monaco in this case 🤦‍♂️
https://github.com/microsoft/monaco-editor/issues/1859

**Comment by moshfeu** [comment]
Better late than ever 😀
I've drafted v0.2.0.
Can you check it? https://github.com/moshfeu/vscode-diff-merge/releases/download/v0.2.0/diff-merge-0.2.0.vsix (https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix)

Thanks!
