### ISSUE TITLE
Add "Compare selected" to context menu of "Open Editors" group

### ISSUE THREAD

**Issue by hansu** [moshfeu/vscode-diff-merge#40]
Selecting two files in the Explorer sidebar by control-click works really nice:

![Bildschirmfoto von 2021-03-23 17-31-35](https://user-images.githubusercontent.com/67957916/112182890-fba7d880-8bfd-11eb-97f3-d56ebd406424.png)

But this context menu is not available in the "Open Editors" group:

![Bildschirmfoto von 2021-03-23 17-31-57](https://user-images.githubusercontent.com/67957916/112182989-14b08980-8bfe-11eb-9c89-31abfc7bc35f.png)

It would be really nice if you could ad that as it is quite necessary to easy compare files from two different directories.

**Comment by moshfeu** [comment]
Thanks for suggestion!
Unfortunately this is [not possible](https://github.com/microsoft/vscode/pull/48983) right now 😕

**Comment by hansu** [comment]
What a pity. 
But you can access the tabs. So what do you think of adding entries like 
[Diff & Merge] Select for Compare
[Diff & Merge] Compare file with selected
as you have already "[Diff & Merge] Compare file with Clipboard" there

**Comment by moshfeu** [comment]
Done.
I'd be happy if you can test it.
[diff-merge-0.5.0.vsix.zip](https://github.com/moshfeu/vscode-diff-merge/files/6382298/diff-merge-0.5.0.vsix.zip)
Thanks

**Comment by hansu** [comment]
Yeah it's working as expected, very nice. Thanks!

A little thing: Does the vscode API allows you to determine whether you are the diff&merge-view or not?
If yes, the entries in the tab context menu could be removed as they have no function at in this point.

**Comment by moshfeu** [comment]
Unfortunately, I don't think it's possible. I can identify when the diff view is the active editor but then all the other tabs' context menu won't include these options since I can click on them even when they are not active.


https://user-images.githubusercontent.com/3723951/117582367-593ea880-b10a-11eb-85b7-2333dff30a87.mov

**Comment by hansu** [comment]
Okay and thanks for your investigation!

**Comment by moshfeu** [comment]
Didn't think of it. Yah, we can do this.
Do you want to open a new issue?
