### ISSUE TITLE
package.json license field

### ISSUE THREAD

**Issue by offa** [moshfeu/vscode-diff-merge#44]
The `package.json` doesn't contain a [`license`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json/#license) field.

**Comment by moshfeu** [comment]
The extension has a [LICENSE file](https://github.com/moshfeu/vscode-diff-merge/blob/4ab6af360fffd2a5f067f43c6f8685bbd0044f2a/LICENSE), isn't good enough?

**Comment by moshfeu** [comment]
Added.
Thanks!

**Comment by offa** [comment]
Thank you!
