### ISSUE TITLE
Merge button is overlapping line numbering when more than 1000 lines

### ISSUE THREAD

**Issue by kt-unzner** [moshfeu/vscode-diff-merge#47]
It is a litte hard to see the merge button (arrow) when the line numbers exceeds 3 digits.
First I wondered why there is no button at this position.

![grafik](https://user-images.githubusercontent.com/68994013/117799570-8f873f80-b252-11eb-887f-07495fcd2dea.png)

**Comment by moshfeu** [comment]
The problem is that the button are patch so the number of line column is not aware of the arrow.
There is enough space in 3 digits numbers of lines but it's a problem in 4 digits.

I'll see what I can do..

**Comment by kt-unzner** [comment]
a) You could move the arrow to the end of the left window (line 997).
b) You could add a background around the arrow that overlays the line number (line 1000). 
But I don't know how far it is possible to influence the colour/style of the icon.
![grafik](https://user-images.githubusercontent.com/68994013/118097939-97bab880-b3d3-11eb-89c5-8310fcadff37.png)

**Comment by moshfeu** [comment]
a) There might be a text of the left side :\
b) I've thought about a similar approach but with opacity and fadein to not hide the line of number entirely.

**Comment by kt-unzner** [comment]
> b) I've thought about a similar approach but with opacity and fadein to not hide the line of number entirely.

Yes, but I think it's more important to see the arrow(s) than the line number(s) because you can easily interpolate the line numbers I think.
