### ISSUE TITLE
[Feature request] Reload Diff & Merge view when file is modified

### ISSUE THREAD

**Issue by kt-unzner** [moshfeu/vscode-diff-merge#48]
When having a Diff & Merge view opened and then editing one of these files in another tab or external, these changed are not recognized. It would be nice if it could be reloaded when changing to the Diff & Merge tab.

Another thing I miss somethimes is a button to toggle the left and the right side.

**Comment by moshfeu** [comment]
Thanks for the issue(s)!

I'll check if it's possible using `workspace.createFileSystemWatcher`

About the swap button. It's there but the icon is missing due changes in the extensions API.
I'm gonna release a patch soon.
