### ISSUE TITLE
Error while comparing files

### ISSUE THREAD

**Issue by a-shkarlatov** [moshfeu/vscode-diff-merge#51]
Hi! I get an error while comparing 2 files when one of them has russian text 

`The file is not displayed in the editor because it is either binary, uses an unsupported text encoding or it's an empty file`

![Screenshot 2021-05-27 165945](https://user-images.githubusercontent.com/42371382/119807142-0ee06880-bf0d-11eb-932b-76e6db6bc926.jpg)

**Comment by moshfeu** [comment]
Thanks for the report!
I will look into it as soon as I can
