### ISSUE TITLE
Theme for comparison is not preserved

### ISSUE THREAD

**Issue by carlosjaramillo-pff** [moshfeu/vscode-diff-merge#54]
If using a dark VS Code theme, the comparison view always uses a white-background theme, which is not visually appealing (for some). For example,

![image](https://user-images.githubusercontent.com/57727112/125858874-1e066201-d5eb-4e45-a96b-7e1019a17bd6.png)

**Comment by moshfeu** [comment]
Thank for the report.
The extension uses an api to get the current theme properties. Maybe this theme does something different
What is this theme?

**Comment by carlosjaramillo-pff** [comment]
I use the "One Dark Pro" theme from https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme

**Comment by moshfeu** [comment]
Thanks, I'll look into it

**Comment by moshfeu** [comment]
I think I fixed that. Can you test please?

[diff-merge-0.5.2.vsix.zip](https://github.com/moshfeu/vscode-diff-merge/files/6850455/diff-merge-0.5.2.vsix.zip)

**Comment by carlosjaramillo-pff** [comment]
Thanks. It seems to work fine now with the attached version!

**Comment by moshfeu** [comment]
Thank you for verifying 🤩
The new version will be available soon.

**Comment by FDiskas** [comment]
Theme: default dark
![image](https://user-images.githubusercontent.com/468006/135330031-1979dadc-39a1-4bc2-a7d3-2e581305bf76.png)
```
Version: 1.61.0-insider
Commit: 4fbe0344a0cedaf2a04edef728c9a3f27777cc6c
Date: 2021-09-29T05:26:17.262Z
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-37-generic snap
```

**Comment by moshfeu** [comment]
@FDiskas I forget to publish this version 🤦‍♂️ I'm doing it right now.
Please update to v0.5.2 and check again.
