### ISSUE TITLE
[Feature Request] Apply all changes

### ISSUE THREAD

**Issue by mystiquewolf** [moshfeu/vscode-diff-merge#59]
Add ability to apply all changes.

**Comment by moshfeu** [comment]
Interesting feature, thanks :)

**Comment by moshfeu** [comment]
When I think of it, it's just coping the left content to the right side, right?

**Comment by mystiquewolf** [comment]
Yes, i think so. VS Code also allows selecting/marking one of the changed "hunks" and selecting to copy them (apply and unapply) separately. Example below. With that said, it's sad that extensions have to implement this instead of it being a core VS Code feature.

![vs code diff example](https://user-images.githubusercontent.com/16529989/150678644-ffdb5347-9a6a-40e3-9bda-ff67667f986e.png)

**Comment by moshfeu** [comment]
Yes :(
https://github.com/microsoft/vscode/issues/25887

**Comment by moshfeu** [comment]
Keep

**Comment by moshfeu** [comment]
Better late than never 😅 .
I'd be happy for you to test this feature.
If it works for you, I'll merge it.

[diff-merge-0.7.0.vsix.zip](https://github.com/moshfeu/vscode-diff-merge/files/8432931/diff-merge-0.7.0.vsix.zip)
