### ISSUE TITLE
Showing blank

### ISSUE THREAD

**Issue by creativemind1** [moshfeu/vscode-diff-merge#6]
I just installed your extension and It is showing blank when I selected two files for Diff & Merging.  
```
VSCode Version: 1.42.1
OS: macOS Catiline Version 10.15
```

**Comment by S77FFY** [comment]
I've been really enjoying using this plugin but it recently has stopped opening.

Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

The first time it launches the two yellow curly brackets appear for a split second and then returns back to a normal new file.

Please let me know what I can do to get the app working again.

Thanks

Ben

**Comment by moshfeu** [comment]
Thank you both!
Actually, I didn't release a version for a while but maybe something changed in the API.
I'll investigate ASAP.

**Comment by moshfeu** [comment]
I pushed a fix (version 0.1.2). Can you check please?
Thanks!

**Comment by creativemind1** [comment]
I confirmed the issue has been fixed and now working perfectly fine at my end. 

This is a very cool extension. You should expand it and include new implementations. Cheers!

**Comment by moshfeu** [comment]
Thanks @creativemind1!
I have some projects and few free time 😅
Feel free to suggest ideas and I'll do my best to add them.
