### ISSUE TITLE
please update on OpenVSX

### ISSUE THREAD

**Issue by GitMensch** [moshfeu/vscode-diff-merge#61]
Hi, it is nice to see that this extension was [published on OpenVSX](https://open-vsx.org/extension/moshfeu/diff-merge) by you, sadly it is outdated (0.5.0, while this extension is currently 0.5.2, soon 0.6.0).

There is also a [GitHub action](https://github.com/HaaLeo/publish-vscode-extension#readme) which allows to publish to both marketplaces by just creating the tag, maybe you are interested in using this.

Additional: Can you please outline in the README why this is "Alpha"?
Shouldn't it be stable enough to be at least "Beta"?

**Comment by moshfeu** [comment]
Thank you for all your great inputs 🙏
I'll get to them as soon as I can
