### ISSUE TITLE
Arrows can't follow movement

### ISSUE THREAD

**Issue by hongshui3000** [moshfeu/vscode-diff-merge#76]
Open file comparison 
![image](https://user-images.githubusercontent.com/25566498/157190849-f7cb41a9-1fc2-43b6-a541-25e220934589.png)
When I drag, the arrow position is still in the original place
![image](https://user-images.githubusercontent.com/25566498/157190977-dde42670-1d4b-4b20-a63f-6d20c611bfa5.png)

![image](https://user-images.githubusercontent.com/25566498/157191374-ef2d7523-11a0-4afc-90c1-1ff12c64c04f.png)

**Comment by moshfeu** [comment]
Thank you, nice catch!
I'll see what I can do 😄
