### ISSUE TITLE
latest version(v0.6.0) not working

### ISSUE THREAD

**Issue by hongshui3000** [moshfeu/vscode-diff-merge#82]
1. Right click on a file [1] in explorer panel or on an editor tab
2.Click [Diff & Merge] Select file to compare
3.Right click on another file or an editor tab
4.Click [Diff & Merge] Compare file with selected file-------->not work，won't show this

**Comment by moshfeu** [comment]
Works for me 🤔

- Can you check with another files? with an older version of the diff-merge?
- Can you check for logs under "OUTPUT > Diff Merge"
- What operation system / machine are you using?

Thanks!

**Comment by hongshui3000** [comment]
> * Can you check with another files? with an older version of the diff-merge?
Other files are also not working in the current version
The previous version is working

> * Can you check for logs under "OUTPUT > Diff Merge"
no log output


> * What operation system / machine are you using?
windows10 


https://user-images.githubusercontent.com/25566498/158091666-3dc02ae7-ad97-4fd1-a082-dde190b492ad.mp4

**Comment by lukeabbott** [comment]
This issue is also occurring for me. Any details I can provide?

**Comment by moshfeu** [comment]
I found the issue.
Now I don't know how it's ever worked or why is it still working in dev environment.
Anyway can you two install this version and let me know if it works?
Thanks!

[diff-merge-0.6.101.vsix.zip](https://github.com/moshfeu/vscode-diff-merge/files/8248667/diff-merge-0.6.101.vsix.zip)
1. Extract the zip
2. Follow this [guide](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix)

**Comment by lukeabbott** [comment]
Will check first thing tomorrow.

**Comment by hongshui3000** [comment]
For me it works fine，thanks.

**Comment by moshfeu** [comment]
Just published v0.6.1 and confirmed it fixed in my end.
Can you verify too?
Thanks

**Comment by lukeabbott** [comment]
Fully fixed on my end.

**Comment by moshfeu** [comment]
Thank you for the confirmation!
