### ISSUE TITLE
Can the font size of this extension be automatically adjusted according to the font size of the vscode code？

### ISSUE THREAD

**Issue by hongshui3000** [moshfeu/vscode-diff-merge#85]
![image](https://user-images.githubusercontent.com/25566498/158297808-9fe5cd48-6037-45d0-81e7-6467cad34c05.png)
Note the difference in fonts

**Comment by moshfeu** [comment]
Thanks.
The extension suppose to take the vscode theme and apply it to the diff view editor (monaco as well).
I'll check why it doesn't take the font-size.
